// Generated by gencpp from file nav_msgs/GetMap.msg
// DO NOT EDIT!


#ifndef NAV_MSGS_MESSAGE_GETMAP_H
#define NAV_MSGS_MESSAGE_GETMAP_H

#include <ros/service_traits.h>


#include <nav_msgs/GetMapRequest.h>
#include <nav_msgs/GetMapResponse.h>


namespace nav_msgs
{

struct GetMap
{

typedef GetMapRequest Request;
typedef GetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMap
} // namespace nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nav_msgs::srv::GetMap > {
  static const char* value()
  {
    return "6cdd0a18e0aff5b0a3ca2326a89b54ff";
  }

  static const char* value(const ::nav_msgs::srv::GetMap&) { return value(); }
};

template<>
struct DataType< ::nav_msgs::srv::GetMap > {
  static const char* value()
  {
    return "nav_msgs/GetMap";
  }

  static const char* value(const ::nav_msgs::srv::GetMap&) { return value(); }
};


// service_traits::MD5Sum< ::nav_msgs::srv::GetMapRequest> should match
// service_traits::MD5Sum< ::nav_msgs::srv::GetMap >
template<>
struct MD5Sum< ::nav_msgs::srv::GetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nav_msgs::srv::GetMap >::value();
  }
  static const char* value(const ::nav_msgs::srv::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_msgs::srv::GetMapRequest> should match
// service_traits::DataType< ::nav_msgs::srv::GetMap >
template<>
struct DataType< ::nav_msgs::srv::GetMapRequest>
{
  static const char* value()
  {
    return DataType< ::nav_msgs::srv::GetMap >::value();
  }
  static const char* value(const ::nav_msgs::srv::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nav_msgs::srv::GetMapResponse> should match
// service_traits::MD5Sum< ::nav_msgs::srv::GetMap >
template<>
struct MD5Sum< ::nav_msgs::srv::GetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nav_msgs::srv::GetMap >::value();
  }
  static const char* value(const ::nav_msgs::srv::GetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_msgs::srv::GetMapResponse> should match
// service_traits::DataType< ::nav_msgs::srv::GetMap >
template<>
struct DataType< ::nav_msgs::srv::GetMapResponse>
{
  static const char* value()
  {
    return DataType< ::nav_msgs::srv::GetMap >::value();
  }
  static const char* value(const ::nav_msgs::srv::GetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAV_MSGS_MESSAGE_GETMAP_H
